### PR TITLE
Laravel 8 support

### PR DESCRIPTION
**Pull request by khatabwedaa**
- Update composer dependencies
- Update home route to class
- Refactor files

### CODE REVIEW

**Comment by Miaababikir** [comment]
Look good for me. 

Sorry for keeping you hanging. I got caught up with my graduation project. I will merge it as soon as I can. Thanks buddy👏😊.

**Comment by FoksVHox** [comment]
> Look good for me.
> 
> Sorry for keeping you hanging. I got caught up with my graduation project. I will merge it as soon as I can. Thanks buddy👏😊.

Any news?

**Comment by Miaababikir** [comment]
@FoksVHox  Sorry for taking so long to get back to you I am releasing it today. Also there is a lot of new features coming I am so exited to wrap it up and release it :fire:

**Comment by FoksVHox** [comment]
> @FoksVHox  Sorry for taking so long to get back to you I am releasing it today. Also there is a lot of new features coming I am so exited to wrap it up and release it :fire: 

Happy to hear, as of right now I've just gone by manual extracting the components, which worked like a charm

**Comment by Miaababikir** [comment]
> > @FoksVHox  Sorry for taking so long to get back to you I am releasing it today. Also there is a lot of new features coming I am so exited to wrap it up and release it fire
> 
> Happy to hear, as of right now I've just gone by manual extracting the components, which worked like a charm

Also if you have any inconveniences with the components or anything else like needing more components just let me know. I am planning to add more components for the next release.

**Comment by FoksVHox** [comment]
> > > @FoksVHox  Sorry for taking so long to get back to you I am releasing it today. Also there is a lot of new features coming I am so exited to wrap it up and release it fire
> > 
> > 
> > Happy to hear, as of right now I've just gone by manual extracting the components, which worked like a charm
> 
> Also if you have any inconveniences with the components or anything else like needing more components just let me know. I am planning to add more components for the next release.

I'll open an issue with the requests

**Pull request merged**
